### ISSUE TITLE
Issue occurring in Clean cmd

### ISSUE THREAD

**Issue by vaibhave-olr** [KiboSoftware/kibo-sandbox-data-cli#5]
Hi,
When we try to execute the clean command, we are getting the below error. Seems like ActiveProfile set it to exportEnv instead of deleteEnv in the node modules. Can you please have a look into it and update?

**kibo-sandbox-data clean --all**

`/home/vaibhav.e/.nvm/versions/node/v18.8.0/lib/node_modules/@kibocommerce/kibo-sandbox-data-cli/bin/index.js:299
 app.setActiveProfile(exportEnv);
                       ^
ReferenceError: exportEnv is not defined
    at clearData (/home/vaibhav.e/.nvm/versions/node/v18.8.0/lib/node_modules/@kibocommerce/kibo-sandbox-data-cli/bin/index.js:299:24)
    at Object.handler (/home/vaibhav.e/.nvm/versions/node/v18.8.0/lib/node_modules/@kibocommerce/kibo-sandbox-data-cli/bin/index.js:101:7)
    at Object.runCommand (/home/vaibhav.e/.nvm/versions/node/v18.8.0/lib/node_modules/@kibocommerce/kibo-sandbox-data-cli/node_modules/yargs/build/index.cjs:446:48)
    at Object.parseArgs [as _parseArgs] (/home/vaibhav.e/.nvm/versions/node/v18.8.0/lib/node_modules/@kibocommerce/kibo-sandbox-data-cli/node_modules/yargs/build/index.cjs:2697:57)
    at Object.get [as argv] (/home/vaibhav.e/.nvm/versions/node/v18.8.0/lib/node_modules/@kibocommerce/kibo-sandbox-data-cli/node_modules/yargs/build/index.cjs:2651:25)
    at Object.<anonymous> (/home/vaibhav.e/.nvm/versions/node/v18.8.0/lib/node_modules/@kibocommerce/kibo-sandbox-data-cli/bin/index.js:127:10)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
`
 

Regards,
Vaibhav

**Comment by vaibhave-olr** [comment]
Hi,
Can we have any update on this? Currently, we are modifying the code in node_modules to make it work. 

Regards,
Vaibhav
